version: '3'
services:
  web:
    build: .
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && bundle exec rails server -p 3000 -b 0.0.0.0"
    volumes:
      - .:/swagger
    ports:
      - "3000:3000"
